apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofka-rabbit
  template:
    metadata:
      labels:
        app: sofka-rabbit
    spec:
      containers:
        - name: sofka-rabbit
          image: rabbitmq:3-management
          resources:
            requests:
              memory: "1000M"
            limits:
              cpu: "1"
              memory: "1000M"
          ports:
            - containerPort: 5672
            - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  type: NodePort
  selector:
    app: sofka-rabbit
  ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30001
    - name: rabbitmq-management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30002
